// 用户指定的固定局域网 CA；私钥随启动器分发，可从源码或二进制提取。
// 仅由局域网 HTTPS 签发模块读取，任何 HTTP 接口不得提供此文件或私钥。
pub(super) const CERTIFICATE_PEM: &[u8] = br#"-----BEGIN CERTIFICATE-----
MIICXTCCAgSgAwIBAgIJAIPt8DwOnB2GMAoGCCqGSM49BAMCMIGBMQswCQYDVQQG
EwJDTjETMBEGA1UECgwKQmluR28gSW5jLjEmMCQGA1UECwwdQmluR28gQ2VydGlm
aWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMMDUJpbkdvIFJvb3QgQ0ExHTAbBgkq
hkiG9w0BCQEWDmFsaXlhQG5iY25tLmNuMB4XDTI2MDExNDEwMDk0NloXDTQ2MDEw
OTEwMDk0NlowgYExCzAJBgNVBAYTAkNOMRMwEQYDVQQKDApCaW5HbyBJbmMuMSYw
JAYDVQQLDB1CaW5HbyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAwwN
QmluR28gUm9vdCBDQTEdMBsGCSqGSIb3DQEJARYOYWxpeWFAbmJjbm0uY24wWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQE6ABQRnTeGn/IKXOkCXTha6bYvf9wIbkq
KvhmA0Xe/P+0gan0YnyGyIN6PMDQ6aL2HmhlOzyVIHXtCTvIPkTWo2MwYTAPBgNV
HRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUQ5vudYajE6pl
XraOwzeRZZ1TzaEwHwYDVR0jBBgwFoAUQ5vudYajE6plXraOwzeRZZ1TzaEwCgYI
KoZIzj0EAwIDRwAwRAIgMOXL5IlxfKQraTEtc84UTkiSs1+EBFCcXiqy8blUB6AC
IAF6N+ALqC4g0P+BNLtIF7GOftg6HmS3EqayA+TlREyU
-----END CERTIFICATE-----
"#;
pub(super) const PRIVATE_KEY_PEM: &[u8] = br#"-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgw1pR3y68PcVEszXt
uFp6BfPHFAeaJvca0MVMltc+R4ShRANCAAQE6ABQRnTeGn/IKXOkCXTha6bYvf9w
IbkqKvhmA0Xe/P+0gan0YnyGyIN6PMDQ6aL2HmhlOzyVIHXtCTvIPkTW
-----END PRIVATE KEY-----
"#;
