package offline.multiplayer;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/** Explicit XML parameters only; missing numbers are -1, never guessed engine defaults. */
public final class WeaponPhysics {
    public static final String SOURCE_SHA256 = "dac0a631e6ad69f52dc0a8f9e4966e51be6b76ebab5bc2262b2be1c3155ccd1b";
    public record Physics(String name, String ammoName, String ammoType,
            double speed, double gravity, double damping, double ricochet, double pedRicochet,
            double vehicleRicochet, double friction, double penetration, double damageTime,
            double damageTimeInVehicle, double damageTimeInVehicleHeadShot,
            long lifetimeMs, long impactDelayMs, long explosionTimeMs,
            boolean sticky, boolean destroyOnImpact, boolean nonLethal,
            String explosion, String ammoFlags, String projectileFlags, String weaponFlags,
            Set<String> explicitFields) {}
    private static final Map<Long, Physics> RULES;
    static {
        var rules = new LinkedHashMap<Long, Physics>();
        rules.put(2725352035L, new Physics("WEAPON_UNARMED", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle CanFreeAim UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DisableLeftHandIkInCover DoesRevivableDamage AllowCloseQuarterKills AllowMeleeIntroAnim HasLowCoverSwaps NoWheelStats QuitTransitionToIdleIntroOnWeaponChange DisableFPSScope AttachFPSLeftHandIKToRight UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4194021054L, new Physics("WEAPON_ANIMAL", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(148160082L, new Physics("WEAPON_COUGAR", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2578778090L, new Physics("WEAPON_KNIFE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle MeleeBlade UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills HasLowCoverSwaps NoWheelStats DangerousLookingMeleeWeapon QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1737195953L, new Physics("WEAPON_NIGHTSTICK", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle MeleeClub UsableOnFoot UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills HasLowCoverSwaps NoWheelStats QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1317494643L, new Physics("WEAPON_HAMMER", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle MeleeClub UsableOnFoot UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills HasLowCoverSwaps NoWheelStats QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2508868239L, new Physics("WEAPON_BAT", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle TwoHanded MeleeClub UsableOnFoot UsableClimbing DoesRevivableDamage AllowCloseQuarterKills NoWheelStats UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1141786504L, new Physics("WEAPON_GOLFCLUB", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle TwoHanded MeleeClub UsableOnFoot UsableClimbing DoesRevivableDamage AllowCloseQuarterKills NoWheelStats UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2227010557L, new Physics("WEAPON_CROWBAR", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle MeleeClub UsableOnFoot UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills HasLowCoverSwaps NoWheelStats QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(453432689L, new Physics("WEAPON_PISTOL", "AMMO_PISTOL", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimReload AnimCrouchFire UsableOnFoot UsableClimbing UsableInCover AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1593441988L, new Physics("WEAPON_COMBATPISTOL", "AMMO_PISTOL", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimReload AnimCrouchFire UsableOnFoot UsableClimbing UsableInCover AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(584646201L, new Physics("WEAPON_APPISTOL", "AMMO_PISTOL", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimReload AnimCrouchFire UsableOnFoot UsableClimbing UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2578377531L, new Physics("WEAPON_PISTOL50", "AMMO_PISTOL", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimReload AnimCrouchFire UsableOnFoot UsableClimbing UsableInCover AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(324215364L, new Physics("WEAPON_MICROSMG", "AMMO_SMG", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimReload AnimCrouchFire TreatAsOneHandedInCover UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps UseLeftHandIkWhenAiming QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion UseAlternateFPDrivebyClipset", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(736523883L, new Physics("WEAPON_SMG", "AMMO_SMG", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4024951519L, new Physics("WEAPON_ASSAULTSMG", "AMMO_SMG", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps UseLeftHandIkWhenAiming TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3220176749L, new Physics("WEAPON_ASSAULTRIFLE", "AMMO_RIFLE", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps TorsoIKForWeaponBlock LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2210333304L, new Physics("WEAPON_CARBINERIFLE", "AMMO_RIFLE", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2937143193L, new Physics("WEAPON_ADVANCEDRIFLE", "AMMO_RIFLE", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2634544996L, new Physics("WEAPON_MG", "AMMO_MG", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2144741730L, new Physics("WEAPON_COMBATMG", "AMMO_MG", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(487013001L, new Physics("WEAPON_PUMPSHOTGUN", "AMMO_SHOTGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ApplyBulletForce Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover NoLeftHandIKWhenBlocked AllowCloseQuarterKills NeedsGunCockingInCover HasLowCoverReloads HasLowCoverSwaps ProcessGripAnim TorsoIKForWeaponBlock LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2017895192L, new Physics("WEAPON_SAWNOFFSHOTGUN", "AMMO_SHOTGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ApplyBulletForce Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover NoLeftHandIKWhenBlocked AllowCloseQuarterKills NeedsGunCockingInCover HasLowCoverReloads HasLowCoverSwaps ProcessGripAnim UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3800352039L, new Physics("WEAPON_ASSAULTSHOTGUN", "AMMO_SHOTGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ApplyBulletForce Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NoLeftHandIKWhenBlocked AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2640438543L, new Physics("WEAPON_BULLPUPSHOTGUN", "AMMO_SHOTGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ApplyBulletForce Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover NoLeftHandIKWhenBlocked AllowCloseQuarterKills NeedsGunCockingInCover HasLowCoverReloads HasLowCoverSwaps LongWeapon UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(911657153L, new Physics("WEAPON_STUNGUN", "AMMO_STUNGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 4.0, 5.0, 5.0, -1L, -1L, -1L, false, false, true, "", "InfiniteAmmo", "", "CarriedInHand Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimCrouchFire UsableOnFoot UsableClimbing UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired DoesRevivableDamage DisplayRechargeTimeHUD OnlyFireOneShot NonLethal AllowCloseQuarterKills DisablePlayerBlockingInMP CanPerformArrest HasLowCoverSwaps DontBreakRopes QuitTransitionToIdleIntroOnWeaponChange DisableLeftHandIkWhenOnFoot TorsoIKForWeaponBlock UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(100416529L, new Physics("WEAPON_SNIPERRIFLE", "AMMO_SNIPER", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand FirstPersonScope Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover HasLowCoverReloads HasLowCoverSwaps UseFPSAimIK UseFPSSecondaryMotion UseFPSAnimatedRecoil DisableFPSAimForScope", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(205991906L, new Physics("WEAPON_HEAVYSNIPER", "AMMO_SNIPER", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand FirstPersonScope Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover HasLowCoverReloads HasLowCoverSwaps IgnoreHelmets DisableFPSAimForScope UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(856002082L, new Physics("WEAPON_REMOTESNIPER", "AMMO_SNIPER_REMOTE", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 100.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Silenced FirstPersonScope Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire UsableOnFoot UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2726580491L, new Physics("WEAPON_GRENADELAUNCHER", "AMMO_GRENADELAUNCHER", "CAmmoProjectileInfo", 25.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 30000L, 1000L, 0L, false, false, false, "GRENADELAUNCHER", "AddSmokeOnExplosion", "ProcessImpacts", "CarriedInHand Gun CanFreeAim TwoHanded Launched AnimReload AnimCrouchFire UsableOnFoot UsableInCover Scary AllowCloseQuarterKills HasLowCoverReloads HasLowCoverSwaps DelayedFiringAfterAutoSwap DisableStealth UseFPSAimIK UseFPSSecondaryMotion", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "FrictionMultiplier", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1305664598L, new Physics("WEAPON_GRENADELAUNCHER_SMOKE", "AMMO_GRENADELAUNCHER_SMOKE", "CAmmoProjectileInfo", 25.0, 1.0, 0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 35000L, 1000L, 30000L, false, false, false, "SMOKEGRENADELAUNCHER", "AddSmokeOnExplosion", "ProcessImpacts", "CarriedInHand ArmourPenetrating Gun CanFreeAim TwoHanded Launched AnimReload AnimCrouchFire UsableOnFoot UsableInCover Scary AllowCloseQuarterKills HasLowCoverSwaps DisableStealth UseFPSAimIK UseFPSSecondaryMotion", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2982836145L, new Physics("WEAPON_RPG", "AMMO_RPG", "CAmmoRocketInfo", 400.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "CarriedInHand Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire CreateVisibleOrdnance UsableOnFoot UsableInCover DisableRightHandIk DisableLeftHandIkInCover Scary DisableIdleVariations HasLowCoverReloads HasLowCoverSwaps RemoveEarlyWhenEnteringVehicles DelayedFiringAfterAutoSwap DisableStealth Rpg UseFPSAimIK UseFPSSecondaryMotion", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(375527679L, new Physics("WEAPON_PASSENGER_ROCKET", "AMMO_RPG", "CAmmoRocketInfo", 400.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "CarriedInHand Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire CreateVisibleOrdnance UsableOnFoot UsableInCover DisableRightHandIk DisableLeftHandIkInCover Scary DisableIdleVariations HasLowCoverSwaps RemoveEarlyWhenEnteringVehicles DelayedFiringAfterAutoSwap", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(324506233L, new Physics("WEAPON_AIRSTRIKE_ROCKET", "AMMO_RPG", "CAmmoRocketInfo", 400.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "CarriedInHand Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire CreateVisibleOrdnance UsableOnFoot UsableInCover DisableRightHandIk DisableLeftHandIkInCover Scary DisableIdleVariations HasLowCoverSwaps RemoveEarlyWhenEnteringVehicles DelayedFiringAfterAutoSwap", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1752584910L, new Physics("WEAPON_STINGER", "AMMO_STINGER", "CAmmoRocketInfo", 400.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 20000L, 0L, 0L, false, true, false, "ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "CarriedInHand Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire CreateVisibleOrdnance UsableOnFoot UsableInCover DisableRightHandIk DisableLeftHandIkInCover Scary DisableIdleVariations HasLowCoverSwaps RemoveEarlyWhenEnteringVehicles DelayedFiringAfterAutoSwap", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1119849093L, new Physics("WEAPON_MINIGUN", "AMMO_MINIGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Gun CanFreeAim Heavy TwoHanded UsableOnFoot AllowEarlyExitFromFireAnimAfterBulletFired ForceEjectShellAfterFiring Scary ForcesActionMode DisableCombatRoll DisableStealth DisableFPSScope UseFPSAimIK UseFPSSecondaryMotion ApplyVehicleDamageToEngine", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2481070269L, new Physics("WEAPON_GRENADE", "AMMO_GRENADE", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 4000L, 0L, 0L, false, false, false, "GRENADE", "AddSmokeOnExplosion Fuse", "ProcessImpacts", "CarriedInHand Silenced CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover AllowCloseQuarterKills HasLowCoverSwaps CookWhileAiming DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope HasFPSProjectileWeaponAnims", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(741814745L, new Physics("WEAPON_STICKYBOMB", "AMMO_STICKYBOMB", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, 0L, 0L, true, false, false, "STICKYBOMB", "AddSmokeOnExplosion", "Sticky ProcessImpacts CanBePlaced NoPullPin CanBeDestroyedByDamage", "CarriedInHand Silenced CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover AllowCloseQuarterKills ManualDetonation HasLowCoverSwaps DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4256991824L, new Physics("WEAPON_SMOKEGRENADE", "AMMO_SMOKEGRENADE", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 5000L, 5000L, false, false, false, "SMOKEGRENADE", "AddSmokeOnExplosion Fuse FixedAfterExplosion", "ProcessImpacts", "CarriedInHand Silenced ArmourPenetrating CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover AllowCloseQuarterKills HasLowCoverSwaps CookWhileAiming DropWhenCooked DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope HasFPSProjectileWeaponAnims", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2694266206L, new Physics("WEAPON_BZGAS", "AMMO_BZGAS", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 5000L, 5000L, false, false, false, "BZGAS", "AddSmokeOnExplosion Fuse FixedAfterExplosion", "ProcessImpacts", "CarriedInHand Silenced ArmourPenetrating CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover AllowCloseQuarterKills HasLowCoverSwaps CookWhileAiming DropWhenCooked DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope HasFPSProjectileWeaponAnims", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(615608432L, new Physics("WEAPON_MOLOTOV", "AMMO_MOLOTOV", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, 0L, 0L, false, false, false, "MOLOTOV", "", "ProcessImpacts TrailFxInactiveOnceWet NoPullPin", "CarriedInHand Silenced ArmourPenetrating CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover ThrowOnly HasLowCoverSwaps DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(101631238L, new Physics("WEAPON_FIREEXTINGUISHER", "AMMO_FIREEXTINGUISHER", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic CanFreeAim AnimCrouchFire UsableOnFoot UsableClimbing AllowEarlyExitFromFireAnimAfterBulletFired DoesRevivableDamage CanBeFiredLikeGun NonViolent SuppressGunshotEvent", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(883325847L, new Physics("WEAPON_PETROLCAN", "AMMO_PETROLCAN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Automatic Silenced AnimCrouchFire UsableOnFoot UsableClimbing AllowEarlyExitFromFireAnimAfterBulletFired CanBeFiredLikeGun OnlyAllowFiring SuppressGunshotEvent NoAutoRunWhenFiring DontBlendFireOutro DiscardWhenOutOfAmmo CreatesAPotentialExplosionEventWhenFired DelayedFiringAfterAutoSwapPreviousWeapon DisableCombatRoll NoWheelStats DisableStealth OnlyUseAimingInfoInFPS EnableFPSRNGOnly AttachFPSLeftHandIKToRight UseFPSAimIK UseFPSSecondaryMotion", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4256881901L, new Physics("WEAPON_DIGISCANNER", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.01, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand Gun CanLockonOnFoot CanLockonInVehicle CanFreeAim AnimReload AnimCrouchFire UsableOnFoot UsableClimbing UsableInCover AllowEarlyExitFromFireAnimAfterBulletFired NonViolent HiddenFromWeaponWheel NoAmmoDisplay EnableFPSIdleOnly UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2803906140L, new Physics("GADGET_NIGHTVISION", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "UsableOnFoot UsableClimbing UsableInCover HiddenFromWeaponWheel", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4222310262L, new Physics("GADGET_PARACHUTE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "HiddenFromWeaponWheel NoAmmoDisplay", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(966099553L, new Physics("OBJECT", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock UsableOnFoot HiddenFromWeaponWheel", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2294779575L, new Physics("WEAPON_BRIEFCASE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand UsableOnFoot HiddenFromWeaponWheel NotAWeapon NoAmmoDisplay DisableCombatRoll NoWheelStats DisableStealth OnlyUseAimingInfoInFPS UseFPSSecondaryMotion EnableFPSIdleOnly", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(28811031L, new Physics("WEAPON_BRIEFCASE_02", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "AllowMeleeBlock CarriedInHand UsableOnFoot HiddenFromWeaponWheel NotAWeapon DisableStealth NoAmmoDisplay EnableFPSIdleOnly", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(600439132L, new Physics("WEAPON_BALL", "AMMO_BALL", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, 0L, 0L, false, false, false, "DONTCARE", "", "ProcessImpacts NoPullPin CanBounce DoubleDamping", "CarriedInHand Silenced CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover DontSwapWeaponIfNoAmmo NonViolent SuppressGunshotEvent NoWheelStats DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1233104067L, new Physics("WEAPON_FLARE", "AMMO_FLARE", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 62500L, 0L, 2500L, false, false, false, "FLARE", "AddSmokeOnExplosion Fuse FixedAfterExplosion", "ProcessImpacts TrailFxInactiveOnceWet NoPullPin DelayUntilSettled", "CarriedInHand Silenced CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover AllowCloseQuarterKills SuppressGunshotEvent HasLowCoverSwaps NoWheelStats DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight DisableFPSScope", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1945616459L, new Physics("VEHICLE_WEAPON_TANK", "AMMO_TANK", "CAmmoProjectileInfo", 400.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 500L, 0L, 0L, false, true, false, "TANKSHELL", "", "DestroyOnImpact ProcessImpacts", "Vehicle StaticReticulePosition EnforceFiringAngularThreshold", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4171469727L, new Physics("VEHICLE_WEAPON_SPACE_ROCKET", "AMMO_SPACE_ROCKET", "CAmmoRocketInfo", 1250.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "PLANE_ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "Gun CanLockonInVehicle Homing Vehicle EnforceAimingRestrictions HomingToggle", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3473446624L, new Physics("VEHICLE_WEAPON_PLANE_ROCKET", "AMMO_PLANE_ROCKET", "CAmmoRocketInfo", 1500.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 10000L, 0L, 0L, false, true, false, "PLANE_ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "Gun CanLockonInVehicle Homing Vehicle EnforceAimingRestrictions HomingToggle", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4026335563L, new Physics("VEHICLE_WEAPON_PLAYER_LASER", "AMMO_PLAYER_LASER", "CAmmoRocketInfo", 1000.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "DONTCARE", "InfiniteAmmo", "DestroyOnImpact HideDrawable TrailFxRemovedOnImpact", "Gun UsableOnFoot Vehicle", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1259576109L, new Physics("VEHICLE_WEAPON_PLAYER_BULLET", "AMMO_MINIGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "Gun UsableOnFoot Vehicle ForceEjectShellAfterFiring", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1186503822L, new Physics("VEHICLE_WEAPON_PLAYER_BUZZARD", "AMMO_MINIGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "Gun UsableOnFoot Vehicle ForceEjectShellAfterFiring ApplyVehicleDamageToEngine", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2669318622L, new Physics("VEHICLE_WEAPON_PLAYER_HUNTER", "AMMO_MINIGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "Gun UsableOnFoot Vehicle", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3800181289L, new Physics("VEHICLE_WEAPON_PLAYER_LAZER", "AMMO_MINIGUN", "CAmmoInfo", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.1, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "Gun UsableOnFoot Vehicle", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1566990507L, new Physics("VEHICLE_WEAPON_ENEMY_LASER", "AMMO_ENEMY_LASER", "CAmmoRocketInfo", 1200.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "DONTCARE", "InfiniteAmmo", "DestroyOnImpact HideDrawable TrailFxRemovedOnImpact", "Gun UsableOnFoot Vehicle", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3450622333L, new Physics("VEHICLE_WEAPON_SEARCHLIGHT", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "OnlyFireOneShotPerTriggerPress Vehicle", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3530961278L, new Physics("VEHICLE_WEAPON_RADAR", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "OnlyFireOneShotPerTriggerPress Vehicle", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3204302209L, new Physics("WEAPON_VEHICLE_ROCKET", "AMMO_RPG", "CAmmoRocketInfo", 400.0, 0.02, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 5000L, 0L, 0L, false, true, false, "ROCKET", "AddSmokeOnExplosion", "DestroyOnImpact ProcessImpacts DoGroundDisturbanceFx", "CarriedInHand Gun CanFreeAim TwoHanded AnimReload AnimCrouchFire CreateVisibleOrdnance UsableOnFoot UsableInCover DisableRightHandIk DisableLeftHandIkInCover Scary DisableIdleVariations HasLowCoverSwaps RemoveEarlyWhenEnteringVehicles DelayedFiringAfterAutoSwap", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1223143800L, new Physics("WEAPON_BARBED_WIRE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4284007675L, new Physics("WEAPON_DROWNING", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "ArmourPenetrating DoesRevivableDamage", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1936677264L, new Physics("WEAPON_DROWNING_IN_VEHICLE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "ArmourPenetrating NoFriendlyFireDamage", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2339582971L, new Physics("WEAPON_BLEEDING", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "ArmourPenetrating DoesRevivableDamage", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2461879995L, new Physics("WEAPON_ELECTRIC_FENCE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 2.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "ArmourPenetrating", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(539292904L, new Physics("WEAPON_EXPLOSION", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3452007600L, new Physics("WEAPON_FALL", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "DoesRevivableDamage UseLegDamageVoice", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(910830060L, new Physics("WEAPON_EXHAUSTION", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "ArmourPenetrating DoesRevivableDamage UseLegDamageVoice", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3425972830L, new Physics("WEAPON_HIT_BY_WATER_CANNON", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "DoesRevivableDamage UseLegDamageVoice", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(133987706L, new Physics("WEAPON_RAMMED_BY_CAR", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "DoesRevivableDamage UseLegDamageVoice", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2741846334L, new Physics("WEAPON_RUN_OVER_BY_CAR", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "DoesRevivableDamage UseLegDamageVoice", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(341774354L, new Physics("WEAPON_HELI_CRASH", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2971687502L, new Physics("VEHICLE_WEAPON_ROTORS", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "DoesRevivableDamage UseLegDamageVoice", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3750660587L, new Physics("WEAPON_FIRE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "ArmourPenetrating", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3854032506L, new Physics("WEAPON_ANIMAL_RETRIEVER", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3146768957L, new Physics("WEAPON_SMALL_DOG", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(743550225L, new Physics("WEAPON_TIGER_SHARK", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3030980043L, new Physics("WEAPON_HAMMERHEAD_SHARK", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4198358245L, new Physics("WEAPON_KILLER_WHALE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(861723357L, new Physics("WEAPON_BOAR", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1205296881L, new Physics("WEAPON_PIG", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1161062353L, new Physics("WEAPON_COYOTE", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(4106648222L, new Physics("WEAPON_DEER", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(955837630L, new Physics("WEAPON_HEN", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(2793925639L, new Physics("WEAPON_RABBIT", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(3799318422L, new Physics("WEAPON_CAT", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(94548753L, new Physics("WEAPON_COW", "NULL", "", -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1L, -1L, -1L, false, false, false, "", "", "", "CarriedInHand ArmourPenetrating CanLockonOnFoot CanLockonInVehicle UsableOnFoot UsableUnderwater UsableClimbing UsableInCover DoesRevivableDamage AllowCloseQuarterKills", Set.of("Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        rules.put(1834887169L, new Physics("WEAPON_BIRD_CRAP", "AMMO_BIRD_CRAP", "CAmmoThrownInfo", 25.0, 1.0, 0.05, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 4000L, 0L, 0L, false, true, false, "EXP_TAG_BIRD_CRAP", "", "DestroyOnImpact ProcessImpacts DontFireAnyEvents", "CarriedInHand Silenced CanLockonOnFoot CanFreeAim AnimReload AnimCrouchFire Thrown UsableOnFoot UsableInCover AllowCloseQuarterKills HasLowCoverSwaps CookWhileAiming DisableLeftHandIkWhenOnFoot UseFPSAimIK UseFPSSecondaryMotion AttachFPSLeftHandIKToRight", Set.of("LaunchSpeed", "GravityFactor", "Damping", "RicochetTolerance", "PedRicochetTolerance", "VehicleRicochetTolerance", "LifeTime", "LifeTimeAfterImpact", "ExplosionTime", "Penetration", "DamageTime", "DamageTimeInVehicle", "DamageTimeInVehicleHeadShot")));
        RULES = Map.copyOf(rules);
    }
    public static Physics byHash(long hash) { return RULES.get(hash & 0xffffffffL); }
    public static Map<Long, Physics> all() { return RULES; }
    private WeaponPhysics() {}
}
