package offline.multiplayer;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Generated by tools/generate_weapon_catalog.py; do not edit the data rows.
 * weapons.meta SHA-256: dac0a631e6ad69f52dc0a8f9e4966e51be6b76ebab5bc2262b2be1c3155ccd1b
 * Blast, melee and legacy damage values are published server gameplay policy.
 * No claim is made to reproduce the binary explosion.ymt or native collision.
 */
public final class WeaponCatalog {
    private WeaponCatalog() {}
    public static final String SOURCE_SHA256 = "dac0a631e6ad69f52dc0a8f9e4966e51be6b76ebab5bc2262b2be1c3155ccd1b";
    public record Rule(long hash, String name, String mode, int damage, long cooldownMillis,
        double range, int pellets, double spread, double speed, double gravity,
        long fuseMillis, long lifetimeMillis, String detonation, double blastRadius,
        long effectDurationMillis, long effectIntervalMillis, int meleeDamage, double meleeRange,
        double assetDamage, String assetFireType, String damageType) {
        public boolean shootable() { return !"melee".equals(mode) && !"environment".equals(mode); }
        public boolean projectile() { return "projectile".equals(mode); }
        public Map<String,Object> publicRule() {
            Map<String,Object> value = new LinkedHashMap<>();
            value.put("weapon",hash); value.put("name",name); value.put("mode",mode);
            value.put("damage",damage); value.put("cooldown_ms",cooldownMillis); value.put("range",range);
            value.put("pellets",pellets); value.put("spread",spread); value.put("speed",speed);
            value.put("gravity",gravity); value.put("fuse_ms",fuseMillis); value.put("lifetime_ms",lifetimeMillis);
            value.put("detonation",detonation); value.put("blast_radius",blastRadius);
            value.put("effect_duration_ms",effectDurationMillis); value.put("effect_interval_ms",effectIntervalMillis);
            value.put("melee_damage",meleeDamage); value.put("melee_range",meleeRange);
            value.put("asset_damage",assetDamage); value.put("asset_fire_type",assetFireType); value.put("damage_type",damageType);
            value.put("collision_model","server_trajectories_world_queries");
            return Collections.unmodifiableMap(value);
        }
    }
    private static final Map<Long,Rule> RULES = create();
    public static Rule rule(long hash) { return RULES.get(hash); }
    public static Map<Long,Rule> rules() { return RULES; }
    public static List<Map<String,Object>> publicRules() { return RULES.values().stream().map(Rule::publicRule).toList(); }
    private static void add(Map<Long,Rule> rules,long hash,String name,String mode,int damage,long cooldown,
        double range,int pellets,double spread,double speed,double gravity,long fuse,long lifetime,
        String detonation,double radius,long duration,long interval,int melee,double meleeRange,
        double assetDamage,String fire,String kind) {
        if(rules.put(hash,new Rule(hash,name,mode,damage,cooldown,range,pellets,spread,speed,gravity,fuse,
            lifetime,detonation,radius,duration,interval,melee,meleeRange,assetDamage,fire,kind))!=null)
            throw new IllegalStateException("Duplicate weapon hash");
    }
    private static Map<Long,Rule> create() {
        Map<Long,Rule> rules = new LinkedHashMap<>();
        add(rules, 0xa2719263L, "WEAPON_UNARMED", "melee", 0, 700, 30.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 20, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xf9fbaebeL, "WEAPON_ANIMAL", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x08d4be52L, "WEAPON_COUGAR", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x99b507eaL, "WEAPON_KNIFE", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 45, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x678b81b1L, "WEAPON_NIGHTSTICK", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x4e875f73L, "WEAPON_HAMMER", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x958a4a8fL, "WEAPON_BAT", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x440e4788L, "WEAPON_GOLFCLUB", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x84bd7bfdL, "WEAPON_CROWBAR", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x1b06d571L, "WEAPON_PISTOL", "hitscan", 25, 200, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 26.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x5ef9fec4L, "WEAPON_COMBATPISTOL", "hitscan", 25, 200, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 27.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x22d8fe39L, "WEAPON_APPISTOL", "hitscan", 25, 200, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 28.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x99aeeb3bL, "WEAPON_PISTOL50", "hitscan", 25, 200, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 51.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x13532244L, "WEAPON_MICROSMG", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 21.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x2be6766bL, "WEAPON_SMG", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 22.0, "INSTANT_HIT", "BULLET");
        add(rules, 0xefe7e2dfL, "WEAPON_ASSAULTSMG", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 23.0, "INSTANT_HIT", "BULLET");
        add(rules, 0xbfefff6dL, "WEAPON_ASSAULTRIFLE", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x83bf0278L, "WEAPON_CARBINERIFLE", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 32.0, "INSTANT_HIT", "BULLET");
        add(rules, 0xaf113f99L, "WEAPON_ADVANCEDRIFLE", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 34.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x9d07f764L, "WEAPON_MG", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x7fd62962L, "WEAPON_COMBATMG", "hitscan", 35, 100, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 32.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x1d073a89L, "WEAPON_PUMPSHOTGUN", "shotgun", 50, 800, 40.0, 8, 0.04, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 29.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x7846a318L, "WEAPON_SAWNOFFSHOTGUN", "shotgun", 50, 800, 40.0, 8, 0.1, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 40.0, "INSTANT_HIT", "BULLET");
        add(rules, 0xe284c527L, "WEAPON_ASSAULTSHOTGUN", "shotgun", 50, 800, 40.0, 8, 0.05, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 32.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x9d61e50fL, "WEAPON_BULLPUPSHOTGUN", "shotgun", 50, 800, 40.0, 8, 0.05, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 14.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x3656c8c1L, "WEAPON_STUNGUN", "hitscan", 1, 2800, 11.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 1.0, "INSTANT_HIT", "ELECTRIC");
        add(rules, 0x05fc3c11L, "WEAPON_SNIPERRIFLE", "hitscan", 100, 1000, 1500, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 101.0, "DELAYED_HIT", "BULLET");
        add(rules, 0x0c472fe2L, "WEAPON_HEAVYSNIPER", "hitscan", 100, 1000, 1500, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 216.0, "DELAYED_HIT", "BULLET");
        add(rules, 0x33058e22L, "WEAPON_REMOTESNIPER", "hitscan", 101, 400, 1500, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 101.0, "DELAYED_HIT", "EXPLOSIVE");
        add(rules, 0xa284510bL, "WEAPON_GRENADELAUNCHER", "projectile", 150, 800, 150.0, 1, 0.0, 25.0, 1.0, 0, 30000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x4dd2dc56L, "WEAPON_GRENADELAUNCHER_SMOKE", "projectile", 0, 800, 25.0, 1, 0.0, 25.0, 1.0, 30000, 30000, "impact", 0, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "NONE");
        add(rules, 0xb1ca77b1L, "WEAPON_RPG", "projectile", 150, 800, 85.0, 1, 0.0, 400.0, 0.02, 0, 5000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x166218ffL, "WEAPON_PASSENGER_ROCKET", "projectile", 150, 800, 85.0, 1, 0.0, 400.0, 0.02, 0, 5000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x13579279L, "WEAPON_AIRSTRIKE_ROCKET", "projectile", 150, 800, 85.0, 1, 0.0, 400.0, 0.02, 0, 5000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x687652ceL, "WEAPON_STINGER", "projectile", 150, 800, 85.0, 1, 0.0, 400.0, 0.02, 0, 20000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x42bf8a85L, "WEAPON_MINIGUN", "hitscan", 25, 20, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x93e220bdL, "WEAPON_GRENADE", "projectile", 150, 500, 30.0, 1, 0.0, 25.0, 1.0, 4000, 4000, "timed", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x2c3731d9L, "WEAPON_STICKYBOMB", "projectile", 150, 500, 30.0, 1, 0.0, 25.0, 1.0, 0, 120000, "remote", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0xfdbc8a50L, "WEAPON_SMOKEGRENADE", "projectile", 0, 500, 30.0, 1, 0.0, 25.0, 1.0, 5000, 5000, "timed", 0, 8000, 1000, 35, 2.0, 0.0, "PROJECTILE", "SMOKE");
        add(rules, 0xa0973d5eL, "WEAPON_BZGAS", "projectile", 10, 500, 30.0, 1, 0.0, 25.0, 1.0, 5000, 5000, "timed", 5, 8000, 1000, 35, 2.0, 0.0, "PROJECTILE", "SMOKE");
        add(rules, 0x24b17070L, "WEAPON_MOLOTOV", "projectile", 20, 500, 30.0, 1, 0.0, 25.0, 1.0, 0, 15000, "impact", 4, 8000, 1000, 35, 2.0, 0.0, "PROJECTILE", "FIRE");
        add(rules, 0x060ec506L, "WEAPON_FIREEXTINGUISHER", "utility", 0, 50, 50.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "VOLUMETRIC_PARTICLE", "FIRE_EXTINGUISHER");
        add(rules, 0x34a67b97L, "WEAPON_PETROLCAN", "utility", 0, 50, 50.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "VOLUMETRIC_PARTICLE", "NONE");
        add(rules, 0xfdbadcedL, "WEAPON_DIGISCANNER", "utility", 0, 333, 50.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "NONE", "BULLET");
        add(rules, 0xa720365cL, "GADGET_NIGHTVISION", "utility", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0xfbab5776L, "GADGET_PARACHUTE", "utility", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x39958261L, "OBJECT", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x88c78eb7L, "WEAPON_BRIEFCASE", "environment", 0, 50, 50.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x01b79f17L, "WEAPON_BRIEFCASE_02", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x23c9f95cL, "WEAPON_BALL", "projectile", 0, 500, 40.0, 1, 0.0, 25.0, 1.0, 0, 15000, "impact", 0, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "NONE");
        add(rules, 0x497facc3L, "WEAPON_FLARE", "projectile", 0, 500, 24.0, 1, 0.0, 25.0, 1.0, 2500, 30000, "impact", 0, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "NONE");
        add(rules, 0x73f7c04bL, "VEHICLE_WEAPON_TANK", "projectile", 150, 2000, 120.0, 1, 0.0, 400.0, 0.0, 0, 500, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0xf8a3939fL, "VEHICLE_WEAPON_SPACE_ROCKET", "projectile", 150, 2000, 300.0, 1, 0.0, 1250.0, 0.02, 0, 5000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0xcf0896e0L, "VEHICLE_WEAPON_PLANE_ROCKET", "projectile", 150, 2000, 300.0, 1, 0.0, 1500.0, 0.02, 0, 10000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0xeffd014bL, "VEHICLE_WEAPON_PLAYER_LASER", "projectile", 40, 500, 120.0, 1, 0.0, 1000.0, 0.0, 0, 5000, "impact", 0, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "ELECTRIC");
        add(rules, 0x4b139b2dL, "VEHICLE_WEAPON_PLAYER_BULLET", "hitscan", 30, 50, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x46b89c8eL, "VEHICLE_WEAPON_PLAYER_BUZZARD", "hitscan", 30, 50, 180.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "BULLET");
        add(rules, 0x9f1a91deL, "VEHICLE_WEAPON_PLAYER_HUNTER", "hitscan", 30, 50, 120.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "EXPLOSIVE");
        add(rules, 0xe2822a29L, "VEHICLE_WEAPON_PLAYER_LAZER", "hitscan", 30, 50, 180.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 30.0, "INSTANT_HIT", "EXPLOSIVE");
        add(rules, 0x5d6660abL, "VEHICLE_WEAPON_ENEMY_LASER", "projectile", 40, 500, 120.0, 1, 0.0, 1200.0, 0.0, 0, 5000, "impact", 0, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "ELECTRIC");
        add(rules, 0xcdac517dL, "VEHICLE_WEAPON_SEARCHLIGHT", "environment", 0, 2000, 50.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "NONE");
        add(rules, 0xd276317eL, "VEHICLE_WEAPON_RADAR", "environment", 0, 2000, 50.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "NONE");
        add(rules, 0xbefdc581L, "WEAPON_VEHICLE_ROCKET", "projectile", 150, 800, 85.0, 1, 0.0, 400.0, 0.02, 0, 5000, "impact", 6, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0x48e7b178L, "WEAPON_BARBED_WIRE", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.1, "NONE", "BARBED_WIRE");
        add(rules, 0xff58c4fbL, "WEAPON_DROWNING", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x736f5990L, "WEAPON_DROWNING_IN_VEHICLE", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x8b7333fbL, "WEAPON_BLEEDING", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x92bd4ebbL, "WEAPON_ELECTRIC_FENCE", "utility", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 20.0, "NONE", "ELECTRIC");
        add(rules, 0x2024f4e8L, "WEAPON_EXPLOSION", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "EXPLOSIVE");
        add(rules, 0xcdc174b0L, "WEAPON_FALL", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x364a29ecL, "WEAPON_EXHAUSTION", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0xcc34325eL, "WEAPON_HIT_BY_WATER_CANNON", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "WATER_CANNON");
        add(rules, 0x07fc7d7aL, "WEAPON_RAMMED_BY_CAR", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0xa36d413eL, "WEAPON_RUN_OVER_BY_CAR", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0x145f1012L, "WEAPON_HELI_CRASH", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "FALL");
        add(rules, 0xb1205a4eL, "VEHICLE_WEAPON_ROTORS", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "UNKNOWN");
        add(rules, 0xdf8e89ebL, "WEAPON_FIRE", "environment", 0, 50, 0.0, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 0, 2.0, 0.0, "NONE", "FIRE");
        add(rules, 0xe5b7de7aL, "WEAPON_ANIMAL_RETRIEVER", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xbb8fe23dL, "WEAPON_SMALL_DOG", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x2c51ad11L, "WEAPON_TIGER_SHARK", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xb4a915cbL, "WEAPON_HAMMERHEAD_SHARK", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xfa3ddce5L, "WEAPON_KILLER_WHALE", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x335cdaddL, "WEAPON_BOAR", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x47d75ef1L, "WEAPON_PIG", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x453467d1L, "WEAPON_COYOTE", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xf4c67a9eL, "WEAPON_DEER", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x38f8ecbeL, "WEAPON_HEN", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xa687ec07L, "WEAPON_RABBIT", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0xe274ff96L, "WEAPON_CAT", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x05a2b311L, "WEAPON_COW", "melee", 0, 700, 1.6, 1, 0.0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2.0, 0.0, "MELEE", "MELEE");
        add(rules, 0x6d5e2801L, "WEAPON_BIRD_CRAP", "projectile", 0, 1000, 30.0, 1, 0.0, 25.0, 1.0, 0, 4000, "impact", 0, 0, 0, 35, 2.0, 0.0, "PROJECTILE", "EXPLOSIVE");
        add(rules, 0xbfd21232L, "WEAPON_SNSPISTOL", "hitscan", 25, 200, 120, 1, 0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2, -1, "COMPATIBILITY", "BULLET");
        add(rules, 0x624fe830L, "WEAPON_COMPACTRIFLE", "hitscan", 35, 100, 120, 1, 0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2, -1, "COMPATIBILITY", "BULLET");
        add(rules, 0xc734385aL, "WEAPON_MARKSMANRIFLE", "hitscan", 100, 1000, 120, 1, 0, 0, 0, 0, 0, "impact", 0, 0, 0, 35, 2, -1, "COMPATIBILITY", "BULLET");
        // The legacy bridge uses zero while an unarmed ped finishes loading.
        Rule unarmed = rules.get(0xa2719263L);
        rules.put(0L,new Rule(0L,"UNARMED_LOADING_ALIAS","melee",0,700,2,1,0,0,0,0,0,
            "impact",0,0,0,unarmed.meleeDamage(),unarmed.meleeRange(),0,"MELEE","MELEE"));
        return Collections.unmodifiableMap(rules);
    }
}
